
logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
jwt.secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
      - id: account-service
        uri: http://localhost:8091
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      - id: customer-service
        uri: http://localhost:8092
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
      - id: order-service
        uri: http://localhost:8090
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
      - id: product-service
        uri: http://localhost:8093
        predicates:
        - Path=/product/**
        filters:
        - RewritePath=/product/(?<path>.*), /$\{path}
      - id: user-service
        uri: http://localhost:8094
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: bank-one-web-api
        uri: http://localhost:9696
        predicates:
        - Path=/baas/**
        filters:
        - RewritePath=/baas/(?<path>.*), /$\{path}

